version: '3.8'

services:
  php:
    build: .
    container_name: php-app
    ports:
      - "80:80" # Mapeia a porta 80 da máquina host para a porta 80 do Apache no container
    volumes:
      - ./src:/var/www/html # Monta o código da aplicação
    environment:
      - AWS_REGION=us-east-1 # Definir a região da AWS

  php_cognito:
    build:
      context: ./php/php_cognito
      dockerfile: Dockerfile
    container_name: php-cognito-app
    ports:
      - "80:80" # Mapeia a porta 81 da máquina host para a porta 81 do Apache no container
    volumes:
      - ./php/php_cognito:/var/www/html # Monta o código da aplicação
    environment:
      - AWS_REGION=us-east-1 # Definir a região da AWS
