# Use a imagem PHP oficial com Apache
FROM php:8.1-apache

# Instale as extensões necessárias
RUN apt-get update && apt-get install -y \
    unzip \
    libzip-dev \
    && docker-php-ext-install mysqli zip

# Instale o Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Defina o diretório de trabalho
WORKDIR /var/www/html

# Copie o código da aplicação para o diretório de trabalho
COPY . /var/www/html/

# Instale as dependências PHP usando o Composer
RUN composer install

# Exponha a porta 80
EXPOSE 81